/** AUTO-GENERATED from plugin "shop-demo" (plugin.json `db`) — DO NOT EDIT. Regenerated by `yarn plugins:sync`. */

export type Scalar = string | number | boolean | Date | null;
export type Filter<V> =
  | V
  | { in: V[] }
  | { notIn: V[] }
  | { not: V }
  | { gt: V }
  | { gte: V }
  | { lt: V }
  | { lte: V }
  | { contains: string };
/** A LIST field takes one question: does it hold this? (a `contains` index answers it) */
export type ListFilter<V> = { has: V };
/** Only INDEXED fields may be filtered — the generator emits the union per model. */
export type Where<T, K extends keyof T> = {
  [P in K]?: T[P] extends readonly (infer E)[] ? ListFilter<E> : T[P] extends Scalar ? Filter<T[P]> : never;
};
export type OrderBy<K extends string> = { [P in K]?: "asc" | "desc" };

export interface FindManyArgs<T, K extends keyof T & string> {
  where?: Where<T, K>;
  orderBy?: OrderBy<K> | OrderBy<K>[];
  take?: number;
  skip?: number;
  cursor?: { id: string };
  includeDeleted?: boolean;
}
export interface AggregateArgs<T, K extends keyof T & string> {
  where?: Where<T, K>;
  _count?: true;
  _sum?: Partial<Record<keyof T & string, true>>;
  _avg?: Partial<Record<keyof T & string, true>>;
  _min?: Partial<Record<keyof T & string, true>>;
  _max?: Partial<Record<keyof T & string, true>>;
}
export interface GroupByArgs<T, K extends keyof T & string> extends AggregateArgs<T, K> {
  by: K[];
}

export interface Collection<Row, Create, K extends keyof Row & string> {
  findMany(args?: FindManyArgs<Row, K>): Promise<Row[]>;
  findFirst(args?: FindManyArgs<Row, K>): Promise<Row | null>;
  findUnique(args: { where: { id: string }; includeDeleted?: boolean }): Promise<Row | null>;
  count(args?: { where?: Where<Row, K>; includeDeleted?: boolean }): Promise<number>;
  aggregate(args?: AggregateArgs<Row, K>): Promise<Record<string, unknown>>;
  groupBy(args: GroupByArgs<Row, K>): Promise<Record<string, unknown>[]>;
  create(args: { data: Create }): Promise<Row>;
  createMany(args: { data: Create[] }): Promise<{ count: number }>;
  update(args: { where: { id: string }; data: Partial<Create> }): Promise<Row>;
  updateMany(args: { where?: Where<Row, K>; data: Partial<Create> }): Promise<{ count: number }>;
  upsert(args: { where: { id: string }; create: Create; update: Partial<Create> }): Promise<Row>;
  delete(args: { where: { id: string } }): Promise<Row>;
  deleteMany(args?: { where?: Where<Row, K> }): Promise<{ count: number }>;
}

export interface ProductRow {
  id: string;
  workspaceId: string;
  nodeId: string;
  ownerId: string | null;
  createdAt: Date;
  updatedAt: Date;
  name: string;
  priceCents: number;
  sku: string | null;
  active: boolean;
  description: string | null;
  tagline: string | null;
  imageUrl: string | null;
  tags: string[];
}
export interface ProductCreate {
  name: string;
  priceCents: number;
  sku?: string | null;
  active?: boolean;
  description?: string | null;
  tagline?: string | null;
  imageUrl?: string | null;
  tags?: string[];
}
export type ProductFilterable = "active" | "createdAt" | "id" | "name" | "ownerId" | "sku" | "tags";

export interface CartLineRow {
  id: string;
  workspaceId: string;
  nodeId: string;
  ownerId: string | null;
  createdAt: Date;
  updatedAt: Date;
  product: string;
  qty: number;
}
export interface CartLineCreate {
  product: string;
  qty?: number;
}
export type CartLineFilterable = "createdAt" | "id" | "ownerId" | "product";

export interface OrderRow {
  id: string;
  workspaceId: string;
  nodeId: string;
  ownerId: string | null;
  createdAt: Date;
  updatedAt: Date;
  status: string;
  totalCents: number;
  lines: unknown;
  shipTo: unknown;
  note: string | null;
  product: string | null;
}
export interface OrderCreate {
  status?: string;
  totalCents: number;
  lines: unknown;
  shipTo: unknown;
  note?: string | null;
  product?: string | null;
}
export type OrderFilterable = "createdAt" | "id" | "ownerId" | "product" | "status";

export interface OrderLineRow {
  id: string;
  workspaceId: string;
  nodeId: string;
  ownerId: string | null;
  createdAt: Date;
  updatedAt: Date;
  order: string;
  product: string | null;
  name: string;
  sku: string | null;
  qty: number;
  priceCents: number;
}
export interface OrderLineCreate {
  order: string;
  product?: string | null;
  name: string;
  sku?: string | null;
  qty: number;
  priceCents: number;
}
export type OrderLineFilterable = "createdAt" | "id" | "order" | "ownerId" | "product";

export interface AddressRow {
  id: string;
  workspaceId: string;
  nodeId: string | null;
  ownerId: string | null;
  createdAt: Date;
  updatedAt: Date;
  label: string;
  lines: unknown;
}
export interface AddressCreate {
  label: string;
  lines: unknown;
}
export type AddressFilterable = "createdAt" | "id" | "ownerId";

export interface ShopDemoDb {
  product: Collection<ProductRow, ProductCreate, ProductFilterable>;
  cartLine: Collection<CartLineRow, CartLineCreate, CartLineFilterable>;
  order: Collection<OrderRow, OrderCreate, OrderFilterable>;
  orderLine: Collection<OrderLineRow, OrderLineCreate, OrderLineFilterable>;
  address: Collection<AddressRow, AddressCreate, AddressFilterable>;
  $transaction<T>(fn: (tx: ShopDemoDb) => Promise<T>): Promise<T>;
}
